//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public BaiViet()
        {
            this.SlideShows = new HashSet<SlideShow>();
        }
    
        public long MaBaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public string NoiDung { get; set; }
        public Nullable<long> MaChuDeBaiViet { get; set; }
        public Nullable<int> MaHienThi { get; set; }
    
        public virtual DMChuDeBaiViet DMChuDeBaiViet { get; set; }
        public virtual DMHienThi DMHienThi { get; set; }
        public virtual ICollection<SlideShow> SlideShows { get; set; }
    }
}
