//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMGioiTinh
    {
        public DMGioiTinh()
        {
            this.GiangViens = new HashSet<GiangVien>();
            this.HocViens = new HashSet<HocVien>();
        }
    
        public int MaGioiTinh { get; set; }
        public string TenGioiTinh { get; set; }
    
        public virtual ICollection<GiangVien> GiangViens { get; set; }
        public virtual ICollection<HocVien> HocViens { get; set; }
    }
}
