//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public GiangVien()
        {
            this.KhoaHoc_GiangVien = new HashSet<KhoaHoc_GiangVien>();
        }
    
        public long MaGiangVien { get; set; }
        public string TenGiangVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TieuSu { get; set; }
        public string HocVi { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> MaGioiTinh { get; set; }
    
        public virtual DMGioiTinh DMGioiTinh { get; set; }
        public virtual ICollection<KhoaHoc_GiangVien> KhoaHoc_GiangVien { get; set; }
    }
}
