//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc
    {
        public KhoaHoc()
        {
            this.KhoaHoc_GiangVien = new HashSet<KhoaHoc_GiangVien>();
            this.SlideShows = new HashSet<SlideShow>();
        }
    
        public long MaKhoaHoc { get; set; }
        public string TenKhoaHoc { get; set; }
        public Nullable<System.DateTime> NgayKhoiTao { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoLuongHocVien { get; set; }
        public Nullable<int> SoLuongBuoiHoc { get; set; }
        public Nullable<int> SoLuongHocTrinh { get; set; }
        public Nullable<int> MaChuDe { get; set; }
        public Nullable<int> MaLoaiKhoaHoc { get; set; }
        public Nullable<int> MaCapHocVien { get; set; }
        public Nullable<int> MaNgonNguLapTrinh { get; set; }
        public string MoTa { get; set; }
        public string AnhKhoaHoc { get; set; }
        public Nullable<int> MaHienThi { get; set; }
        public Nullable<decimal> HocPhi { get; set; }
    
        public virtual DMCapHocVien DMCapHocVien { get; set; }
        public virtual DMChuDe DMChuDe { get; set; }
        public virtual DMHienThi DMHienThi { get; set; }
        public virtual DMLoaiKhoaHoc DMLoaiKhoaHoc { get; set; }
        public virtual DMNgonNguLapTrinh DMNgonNguLapTrinh { get; set; }
        public virtual ICollection<KhoaHoc_GiangVien> KhoaHoc_GiangVien { get; set; }
        public virtual ICollection<SlideShow> SlideShows { get; set; }
    }
}
