//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideShow
    {
        public int MaSlide { get; set; }
        public string TenSlide { get; set; }
        public Nullable<long> MaKhoaHoc { get; set; }
        public Nullable<long> MaBaiViet { get; set; }
        public string AnhSlide { get; set; }
        public Nullable<int> MaHienThi { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
