//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMHienThi
    {
        public DMHienThi()
        {
            this.BaiViets = new HashSet<BaiViet>();
            this.KhoaHocs = new HashSet<KhoaHoc>();
        }
    
        public int MaHienThi { get; set; }
        public string TenHienThi { get; set; }
    
        public virtual ICollection<BaiViet> BaiViets { get; set; }
        public virtual ICollection<KhoaHoc> KhoaHocs { get; set; }
    }
}
