//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVien
    {
        public long MaHocVien { get; set; }
        public string TenHocVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string CMTND { get; set; }
        public string NoiSinh { get; set; }
        public Nullable<int> MaCapHocVien { get; set; }
        public Nullable<int> MaGioiTinh { get; set; }
    
        public virtual DMGioiTinh DMGioiTinh { get; set; }
    }
}
