//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QuanTriVien
    {
        [Required(ErrorMessage = "Mã quản trị bắt buộc nhập")]
        [Display(Name = "Mã quản trị viên")]
        public long MaQuanTriVien { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập bắt buộc nhập")]
        [Display(Name = "Tên đăng nhập")]
        public string TenDangNhap { get; set; }

        [Display(Name = "Tên hiển thị")]
        public string TenHienThi { get; set; }
        [Required(ErrorMessage = "Mật khẩu bắt buộc nhập")]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }

        
        public Nullable<int> MaQuyenQuanTri { get; set; }

        [Display(Name = "Tên quyền quản trị")]
        public virtual DMQuyenQuanTri DMQuyenQuanTri { get; set; }
    }
}
