//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Runtime.Remoting.Contexts;

namespace WebMVC.DataAccessLayer
{

    public partial class WebMVC_ModelDbContext : System.Data.Entity.DbContext
    {
        public WebMVC_ModelDbContext()
            : base("name=Database_EducationEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaiViet> BaiViets { get; set; }
        public DbSet<DMCapHocVien> DMCapHocViens { get; set; }
        public DbSet<DMChuDe> DMChuDes { get; set; }
        public DbSet<DMChuDeBaiViet> DMChuDeBaiViets { get; set; }
        public DbSet<DMGioiTinh> DMGioiTinhs { get; set; }
        public DbSet<DMHienThi> DMHienThis { get; set; }
        public DbSet<DMLoaiKhoaHoc> DMLoaiKhoaHocs { get; set; }
        public DbSet<DMNgonNguLapTrinh> DMNgonNguLapTrinhs { get; set; }
        public DbSet<DMQuyenQuanTri> DMQuyenQuanTris { get; set; }
        public DbSet<GiangVien> GiangViens { get; set; }
        public DbSet<HocVien> HocViens { get; set; }
        public DbSet<KhoaHoc> KhoaHocs { get; set; }
        public DbSet<KhoaHoc_GiangVien> KhoaHoc_GiangVien { get; set; }
        public DbSet<QuanTriVien> QuanTriViens { get; set; }
        public DbSet<SlideShow> SlideShows { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
